### PR TITLE
支持集群

### PR DESCRIPTION
**Pull request by sssession**
添加 connectString 参数支持 kafka 和 zookeeper 集群

### CODE REVIEW

**Comment by zuoez02** [comment]
@sssession Not bad idea. But I suggest using connectionString instead of connectString because it is using in kafka-node README file.

Why using connectionString can support cluster?

Sorry my Chinese input method is broken on my computer.

**Comment by sssession** [comment]
>  @example <caption>Chrooted connection to multiple zookeeper hosts</caption>
>  var client = new Client('localhost:2181,localhost:2182/exmaple/chroot

连接多个 host zookeeper 时可以改用 ‘，’ 隔开。

[https://github.com/SOHU-Co/kafka-node/blob/master/lib/client.js#L34](https://github.com/SOHU-Co/kafka-node/blob/master/lib/client.js#L34)

**Comment by sssession** [comment]
@zuoez02 还没有 publish 到 npm 仓库

**Comment by zuoez02** [comment]
@sssession 现在publish了，抱歉拖了一些时间

**Pull request merged**
